# Generated by Django 2.1.1 on 2018-11-17 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='시리얼넘버')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='구입일자')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='구입가격')),
                ('status', models.SmallIntegerField(choices=[(0, '사용 가능'), (20, '사용 중'), (10, '사용 승인 대기 중'), (11, '반납 승인 대기 중')], default=0, verbose_name='상태')),
                ('management_number', models.CharField(max_length=50, verbose_name='관리번호')),
                ('accessibility', models.SmallIntegerField(choices=[(0, '개인용'), (1, '공용')], default=0, verbose_name='용도')),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True, verbose_name='제조사')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='모델')),
                ('purpose', models.TextField(verbose_name='사용용도')),
                ('check_in_duedate', models.DateField(blank=True, null=True, verbose_name='반납예정일')),
                ('buying_shop', models.CharField(blank=True, max_length=50, null=True, verbose_name='구입처')),
                ('document', models.CharField(blank=True, max_length=100, null=True, verbose_name='관련문서')),
                ('current_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_user', to=settings.AUTH_USER_MODEL, verbose_name='현재 사용자')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateField(auto_now_add=True, verbose_name='사용신청일')),
                ('purpose', models.TextField(verbose_name='사용 목적')),
                ('check_in_duedate', models.DateField(verbose_name='반납 예정일')),
                ('note', models.TextField(blank=True, null=True, verbose_name='기타')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='사용 신청 거절 이유')),
                ('status', models.SmallIntegerField(choices=[(0, '사용 신청 검토중'), (10, '사용 승인'), (20, '사용 거절'), (30, '사용 신청 취소')], default=0, verbose_name='상태')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.Equipment', verbose_name='신청장비')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용신청자')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out_date', models.DateField(null=True, verbose_name='반출일자')),
                ('purpose', models.CharField(max_length=50, null=True, verbose_name='용도')),
                ('check_in_duedate', models.DateField(null=True, verbose_name='반납예정일')),
                ('manager_confirm', models.CharField(max_length=20, null=True, verbose_name='반출자확인')),
                ('check_in_confirm', models.CharField(max_length=20, null=True, verbose_name='반납확인')),
                ('note', models.TextField(null=True, verbose_name='비고')),
                ('count', models.SmallIntegerField(null=True, verbose_name='Count')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.Equipment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['check_out_date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentRepairHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='일자')),
                ('reason', models.TextField(verbose_name='고장사유및내역')),
                ('result', models.CharField(max_length=100, verbose_name='처리결과')),
                ('cost', models.IntegerField(verbose_name='비용')),
                ('reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='관련근거')),
                ('count', models.SmallIntegerField(verbose_name='Count')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.Equipment')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateField(auto_now_add=True, verbose_name='반납신청일')),
                ('reason', models.TextField(verbose_name='반납사유')),
                ('note', models.TextField(blank=True, null=True, verbose_name='기타')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='반납신청 거절이유')),
                ('status', models.SmallIntegerField(choices=[(0, '반납 신청 검토중'), (10, '반납 승인'), (20, '반납 거절'), (30, '반납 신청 취소')], default=0, verbose_name='상태')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.Equipment', verbose_name='신청장비')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='반납신청자')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPU')),
                ('mem', models.CharField(blank=True, max_length=50, null=True, verbose_name='메모리')),
                ('hdd', models.CharField(blank=True, max_length=50, null=True, verbose_name='HDD')),
                ('nic', models.CharField(blank=True, max_length=50, null=True, verbose_name='네트워크')),
                ('graphic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Graphic')),
                ('etc', models.CharField(blank=True, max_length=50, null=True, verbose_name='기타')),
                ('text', models.CharField(blank=True, max_length=50, null=True, verbose_name='텍스트')),
                ('change_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='변경날짜')),
                ('change_reason', models.CharField(blank=True, max_length=50, null=True, verbose_name='변경사유및내역')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='소요비용')),
                ('reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='관련근거')),
                ('count', models.SmallIntegerField(blank=True, null=True, verbose_name='Count')),
                ('change_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_user', to=settings.AUTH_USER_MODEL, verbose_name='담당')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RepairStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='equipmenttype',
            unique_together={('id', 'label')},
        ),
        migrations.AddField(
            model_name='equipment',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.EquipmentType', verbose_name='종류'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_manager', to=settings.AUTH_USER_MODEL, verbose_name='구매담당자'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_request_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_user', to=settings.AUTH_USER_MODEL, verbose_name='구입요청자'),
        ),
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together={('serial_number', 'management_number')},
        ),
    ]
