# Generated by Django 2.1.1 on 2018-10-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='accessibility',
            field=models.SmallIntegerField(choices=[(0, '개인용'), (1, '공용')], default=0, verbose_name='용도'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='check_in_duedate',
            field=models.DateField(blank=True, null=True, verbose_name='반납예정일'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='document',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관련문서'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='제조사'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='모델'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='구입가격'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='구입일자'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='시리얼넘버'),
        ),
    ]
