# Generated by Django 2.1.1 on 2018-10-14 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_auto_20181013_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentspec',
            name='change_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_user', to=settings.AUTH_USER_MODEL, verbose_name='담당'),
        ),
        migrations.AlterField(
            model_name='equipmentspec',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='소요비용'),
        ),
        migrations.AlterField(
            model_name='equipmentspec',
            name='count',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Count'),
        ),
    ]
