# Generated by Django 2.1.1 on 2018-10-21 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ems', '0003_auto_20181014_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(verbose_name='사용 목적')),
                ('check_in_duedate', models.DateField(verbose_name='반납 예정일')),
                ('note', models.TextField(blank=True, null=True, verbose_name='기타')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='사용 신청 거절 이유')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.Equipment', verbose_name='신청장비')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용신청자')),
            ],
        ),
    ]
