# Generated by Django 2.1.1 on 2018-10-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0004_equipmentapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentapply',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '사용 신청 검토중'), (10, '사용 승인'), (20, '사용 거절')], default=0, verbose_name='상태'),
        ),
    ]
