# Generated by Django 2.1.1 on 2018-10-22 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ems', '0006_auto_20181021_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateField(auto_now_add=True, verbose_name='반납신청일')),
                ('reason', models.TextField(verbose_name='반납사유')),
                ('note', models.TextField(blank=True, null=True, verbose_name='기타')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='반납신청 거절이유')),
                ('status', models.SmallIntegerField(choices=[(0, '반납 신청 검토중'), (10, '반납 승인'), (20, '반납 거절'), (30, '반납 신청 취소')], default=0, verbose_name='상태')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.Equipment', verbose_name='신청장비')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='반납신청자')),
            ],
        ),
    ]
